TOPLEVEL_LANG = vhdl
SIM = ghdl
SIM_ARGS = --wave=wave.ghw

VHDL_SOURCES = $(PWD)/axilt_ram.vhd
COCOTB_TOPLEVEL = axilt_ram
COCOTB_TEST_MODULES = axilt_ram_tb

include $(shell cocotb-config --makefiles)/Makefile.sim