TOPLEVEL_LANG = vhdl
SIM = ghdl
SIM_ARGS = --wave=wave.ghw

VHDL_SOURCES = $(PWD)/adder_8bit.vhd
COCOTB_TOPLEVEL = adder_8bit
COCOTB_TEST_MODULES = full_adder_tb

include $(shell cocotb-config --makefiles)/Makefile.sim